name: Publish library

on:
  push:
    branches: [ "main" ]

jobs:
  
  build:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build & Test
        run: |
          chmod +x gradlew
          ./gradlew build allTests

      - name: Publish package
        run: ./gradlew publishAllPublicationsToGithubPackagesRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
